'use client';

import { useState, useMemo } from 'react';
import {
  FileText,
  Download,
  Calendar,
  Filter,
  Play,
  Clock,
  Plus,
  ChevronDown,
  Users,
  MapPin,
  Trash2,
  BarChart3,
  DollarSign,
  UserCheck,
  XCircle,
  TrendingUp,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// ═══════════════════ TYPES ═══════════════════

type ReportType =
  | 'production'
  | 'collections'
  | 'demographics'
  | 'treatment_acceptance'
  | 'no_show'
  | 'aging';

interface ReportConfig {
  label: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  iconBg: string;
  iconColor: string;
}

interface ScheduledReport {
  id: string;
  name: string;
  type: ReportType;
  frequency: string;
  nextRun: string;
  recipients: string;
}

// ═══════════════════ CONSTANTS ═══════════════════

const REPORT_TYPES: Record<ReportType, ReportConfig> = {
  production: {
    label: 'Production Report',
    description: 'Revenue generated by procedures, providers, and time period',
    icon: DollarSign,
    iconBg: 'bg-teal-50',
    iconColor: 'text-teal-600',
  },
  collections: {
    label: 'Collections Report',
    description: 'Payments received, adjustments, and outstanding balances',
    icon: TrendingUp,
    iconBg: 'bg-green-50',
    iconColor: 'text-green-600',
  },
  demographics: {
    label: 'Patient Demographics',
    description: 'Patient population analysis by age, insurance, and status',
    icon: Users,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
  },
  treatment_acceptance: {
    label: 'Treatment Acceptance',
    description: 'Treatment plan acceptance rates and pending treatments',
    icon: UserCheck,
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-600',
  },
  no_show: {
    label: 'No-Show Rate',
    description: 'Appointment no-show and cancellation analysis',
    icon: XCircle,
    iconBg: 'bg-red-50',
    iconColor: 'text-red-600',
  },
  aging: {
    label: 'Aging Report',
    description: 'Outstanding accounts receivable by aging bucket',
    icon: Clock,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-600',
  },
};

const PROVIDERS = ['All Providers', 'Dr. Smith', 'Dr. Johnson', 'Dr. Williams'];
const LOCATIONS = ['All Locations', 'Main Office', 'Downtown Branch'];

// ═══════════════════ MOCK REPORT DATA ═══════════════════

function generateMockData(type: ReportType): { headers: string[]; rows: string[][] } {
  switch (type) {
    case 'production':
      return {
        headers: ['Date', 'Provider', 'CDT Code', 'Description', 'Patient', 'Amount'],
        rows: [
          ['06/01/2026', 'Dr. Smith', 'D2740', 'Crown - porcelain/ceramic', 'Sarah Johnson', '$1,250.00'],
          ['06/01/2026', 'Dr. Smith', 'D0120', 'Periodic oral evaluation', 'Michael Chen', '$65.00'],
          ['06/01/2026', 'Dr. Williams', 'D3330', 'Endodontic therapy, molar', 'Emily Rodriguez', '$1,150.00'],
          ['06/01/2026', 'Dr. Johnson', 'D1110', 'Prophylaxis - adult', 'James Wilson', '$110.00'],
          ['05/31/2026', 'Dr. Smith', 'D2391', 'Resin composite - 1 surface', 'Lisa Thompson', '$210.00'],
          ['05/31/2026', 'Dr. Williams', 'D4341', 'SRP - per quadrant', 'David Park', '$285.00'],
          ['05/31/2026', 'Dr. Johnson', 'D7140', 'Extraction, erupted tooth', 'Amanda Foster', '$225.00'],
          ['05/30/2026', 'Dr. Smith', 'D2750', 'Crown - PFM high noble', 'Robert Kim', '$1,350.00'],
          ['05/30/2026', 'Dr. Williams', 'D0330', 'Panoramic radiograph', 'Sarah Johnson', '$130.00'],
          ['05/30/2026', 'Dr. Johnson', 'D2950', 'Core buildup', 'Michael Chen', '$320.00'],
        ],
      };
    case 'collections':
      return {
        headers: ['Date', 'Patient', 'Invoice #', 'Charge', 'Payment', 'Adjustment', 'Balance'],
        rows: [
          ['06/01/2026', 'Sarah Johnson', 'INV-1051', '$1,250.00', '$500.00', '$0.00', '$750.00'],
          ['06/01/2026', 'Michael Chen', 'INV-1049', '$65.00', '$65.00', '$0.00', '$0.00'],
          ['05/31/2026', 'Emily Rodriguez', 'INV-1048', '$1,150.00', '$0.00', '$0.00', '$1,150.00'],
          ['05/31/2026', 'James Wilson', 'INV-1047', '$110.00', '$110.00', '$0.00', '$0.00'],
          ['05/30/2026', 'Lisa Thompson', 'INV-1045', '$210.00', '$210.00', '$0.00', '$0.00'],
          ['05/30/2026', 'David Park', 'INV-1044', '$285.00', '$150.00', '$0.00', '$135.00'],
          ['05/29/2026', 'Amanda Foster', 'INV-1043', '$225.00', '$225.00', '$0.00', '$0.00'],
          ['05/29/2026', 'Robert Kim', 'INV-1042', '$1,350.00', '$675.00', '$50.00', '$625.00'],
        ],
      };
    case 'demographics':
      return {
        headers: ['Age Group', 'Patient Count', '% of Total', 'Avg Visits/Year', 'Insurance Type'],
        rows: [
          ['0-17', '145', '11.3%', '2.1', 'PPO (65%), Medicaid (25%), Other (10%)'],
          ['18-34', '312', '24.3%', '1.6', 'PPO (58%), HMO (22%), Self-Pay (20%)'],
          ['35-49', '298', '23.2%', '1.9', 'PPO (62%), HMO (18%), Self-Pay (20%)'],
          ['50-64', '285', '22.2%', '2.3', 'PPO (55%), HMO (15%), Medicare (20%), Self-Pay (10%)'],
          ['65+', '244', '19.0%', '2.5', 'Medicare (48%), PPO (32%), Self-Pay (20%)'],
        ],
      };
    case 'treatment_acceptance':
      return {
        headers: ['Provider', 'Plans Presented', 'Plans Accepted', 'Acceptance Rate', 'Value Presented', 'Value Accepted'],
        rows: [
          ['Dr. Smith', '45', '32', '71.1%', '$68,500', '$48,200'],
          ['Dr. Johnson', '38', '24', '63.2%', '$52,300', '$33,100'],
          ['Dr. Williams', '42', '35', '83.3%', '$61,800', '$51,500'],
          ['All Providers', '125', '91', '72.8%', '$182,600', '$132,800'],
        ],
      };
    case 'no_show':
      return {
        headers: ['Provider', 'Total Scheduled', 'Completed', 'No-Shows', 'Cancellations', 'No-Show Rate'],
        rows: [
          ['Dr. Smith', '165', '148', '8', '9', '4.8%'],
          ['Dr. Johnson', '142', '124', '10', '8', '7.0%'],
          ['Dr. Williams', '158', '145', '6', '7', '3.8%'],
          ['Lisa M. (RDH)', '120', '108', '5', '7', '4.2%'],
          ['Sarah K. (RDH)', '115', '105', '4', '6', '3.5%'],
          ['All Staff', '700', '630', '33', '37', '4.7%'],
        ],
      };
    case 'aging':
      return {
        headers: ['Aging Bucket', 'Accounts', 'Total Amount', '% of Total', 'Avg per Account'],
        rows: [
          ['Current (0 days)', '42', '$18,500', '35.2%', '$440.48'],
          ['1-30 days', '28', '$12,800', '24.4%', '$457.14'],
          ['31-60 days', '15', '$8,900', '17.0%', '$593.33'],
          ['61-90 days', '8', '$6,200', '11.8%', '$775.00'],
          ['90+ days', '6', '$6,100', '11.6%', '$1,016.67'],
          ['Total', '99', '$52,500', '100%', '$530.30'],
        ],
      };
  }
}

const MOCK_SCHEDULED: ScheduledReport[] = [
  {
    id: '1',
    name: 'Monthly Production Summary',
    type: 'production',
    frequency: 'Monthly (1st)',
    nextRun: '2026-07-01',
    recipients: 'office@brightsmile.com',
  },
  {
    id: '2',
    name: 'Weekly No-Show Report',
    type: 'no_show',
    frequency: 'Weekly (Mon)',
    nextRun: '2026-06-08',
    recipients: 'manager@brightsmile.com',
  },
  {
    id: '3',
    name: 'Quarterly Aging Report',
    type: 'aging',
    frequency: 'Quarterly',
    nextRun: '2026-07-01',
    recipients: 'billing@brightsmile.com',
  },
];

// ═══════════════════ MAIN PAGE ═══════════════════

export default function ReportsBuilderPage() {
  const [selectedType, setSelectedType] = useState<ReportType>('production');
  const [startDate, setStartDate] = useState('2026-05-01');
  const [endDate, setEndDate] = useState('2026-06-01');
  const [provider, setProvider] = useState('All Providers');
  const [location, setLocation] = useState('All Locations');
  const [hasGenerated, setHasGenerated] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const reportData = useMemo(() => generateMockData(selectedType), [selectedType]);
  const config = REPORT_TYPES[selectedType];

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setHasGenerated(true);
    }, 800);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-stone-900">Reports Builder</h1>
        <p className="mt-1 text-sm text-stone-500">
          Generate, preview, and export practice reports
        </p>
      </div>

      {/* Report Type Selector */}
      <div className="rounded-xl border border-stone-200 bg-white shadow-sm">
        <div className="border-b border-stone-100 px-6 py-4">
          <h2 className="text-base font-semibold text-stone-900">
            Select Report Type
          </h2>
        </div>
        <div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-3 lg:grid-cols-6">
          {(Object.entries(REPORT_TYPES) as [ReportType, ReportConfig][]).map(
            ([type, cfg]) => {
              const Icon = cfg.icon;
              return (
                <button
                  key={type}
                  onClick={() => {
                    setSelectedType(type);
                    setHasGenerated(false);
                  }}
                  className={cn(
                    'flex flex-col items-center gap-2 rounded-xl border p-4 text-center transition-colors',
                    selectedType === type
                      ? 'border-teal-500 bg-teal-50 ring-1 ring-teal-500'
                      : 'border-stone-200 hover:border-stone-300 hover:bg-stone-50'
                  )}
                >
                  <div className={cn('rounded-lg p-2', cfg.iconBg)}>
                    <Icon className={cn('h-5 w-5', cfg.iconColor)} />
                  </div>
                  <span
                    className={cn(
                      'text-xs font-medium',
                      selectedType === type
                        ? 'text-teal-700'
                        : 'text-stone-700'
                    )}
                  >
                    {cfg.label}
                  </span>
                </button>
              );
            }
          )}
        </div>
      </div>

      {/* Filters */}
      <div className="rounded-xl border border-stone-200 bg-white shadow-sm">
        <div className="border-b border-stone-100 px-6 py-4">
          <h2 className="text-base font-semibold text-stone-900">
            Report Parameters
          </h2>
          <p className="mt-0.5 text-xs text-stone-500">{config.description}</p>
        </div>
        <div className="flex flex-wrap items-end gap-4 p-4">
          {/* Date Range */}
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-stone-500">
              Start Date
            </label>
            <div className="flex items-center gap-2 rounded-lg border border-stone-300 bg-white px-3 py-2">
              <Calendar className="h-4 w-4 text-stone-400" />
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="border-0 bg-transparent text-sm text-stone-700 focus:outline-none"
              />
            </div>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-stone-500">
              End Date
            </label>
            <div className="flex items-center gap-2 rounded-lg border border-stone-300 bg-white px-3 py-2">
              <Calendar className="h-4 w-4 text-stone-400" />
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="border-0 bg-transparent text-sm text-stone-700 focus:outline-none"
              />
            </div>
          </div>

          {/* Provider */}
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-stone-500">
              Provider
            </label>
            <select
              value={provider}
              onChange={(e) => setProvider(e.target.value)}
              className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm text-stone-700 focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500"
            >
              {PROVIDERS.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </div>

          {/* Location */}
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-stone-500">
              Location
            </label>
            <select
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              className="rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm text-stone-700 focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500"
            >
              {LOCATIONS.map((l) => (
                <option key={l} value={l}>
                  {l}
                </option>
              ))}
            </select>
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 rounded-lg bg-teal-600 px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-teal-700 disabled:cursor-not-allowed disabled:bg-stone-300"
          >
            {isGenerating ? (
              <>
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                Generating...
              </>
            ) : (
              <>
                <Play className="h-4 w-4" />
                Generate Report
              </>
            )}
          </button>
        </div>
      </div>

      {/* Report Preview */}
      {hasGenerated ? (
        <div className="rounded-xl border border-stone-200 bg-white shadow-sm">
          <div className="flex items-center justify-between border-b border-stone-100 px-6 py-4">
            <div className="flex items-center gap-3">
              <div className={cn('rounded-lg p-2', config.iconBg)}>
                {(() => {
                  const Icon = config.icon;
                  return <Icon className={cn('h-5 w-5', config.iconColor)} />;
                })()}
              </div>
              <div>
                <h2 className="text-base font-semibold text-stone-900">
                  {config.label}
                </h2>
                <p className="text-xs text-stone-500">
                  {startDate} to {endDate} | {provider} | {location}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button className="flex items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm font-medium text-stone-600 transition-colors hover:bg-stone-50">
                <Download className="h-4 w-4" />
                Export CSV
              </button>
              <button className="flex items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm font-medium text-stone-600 transition-colors hover:bg-stone-50">
                <FileText className="h-4 w-4" />
                Export PDF
              </button>
            </div>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-stone-200 bg-stone-50">
                  {reportData.headers.map((header) => (
                    <th
                      key={header}
                      className="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-stone-500"
                    >
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {reportData.rows.map((row, i) => (
                  <tr
                    key={i}
                    className={cn(
                      'border-b border-stone-50 transition-colors hover:bg-stone-50',
                      i === reportData.rows.length - 1 &&
                        (selectedType === 'treatment_acceptance' ||
                          selectedType === 'no_show' ||
                          selectedType === 'aging') &&
                        'bg-stone-50 font-medium'
                    )}
                  >
                    {row.map((cell, j) => (
                      <td
                        key={j}
                        className={cn(
                          'px-5 py-3',
                          j === 0
                            ? 'font-medium text-stone-900'
                            : 'text-stone-700'
                        )}
                      >
                        {cell}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <div className="rounded-xl border border-stone-200 bg-white py-16 text-center shadow-sm">
          <BarChart3 className="mx-auto h-12 w-12 text-stone-300" />
          <h3 className="mt-3 text-sm font-medium text-stone-700">
            No report generated yet
          </h3>
          <p className="mt-1 text-xs text-stone-500">
            Select a report type, set your parameters, and click Generate Report.
          </p>
        </div>
      )}

      {/* Scheduled Reports */}
      <div className="rounded-xl border border-stone-200 bg-white shadow-sm">
        <div className="flex items-center justify-between border-b border-stone-100 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="rounded-lg bg-stone-100 p-2">
              <Clock className="h-5 w-5 text-stone-500" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-stone-900">
                Scheduled Reports
              </h2>
              <p className="text-xs text-stone-500">
                Automatically generated and delivered reports
              </p>
            </div>
          </div>
          <button className="flex items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm font-medium text-stone-600 transition-colors hover:bg-stone-50">
            <Plus className="h-4 w-4" />
            Schedule Report
          </button>
        </div>

        {MOCK_SCHEDULED.length === 0 ? (
          <div className="py-12 text-center">
            <Clock className="mx-auto h-10 w-10 text-stone-300" />
            <h3 className="mt-3 text-sm font-medium text-stone-700">
              No scheduled reports
            </h3>
            <p className="mt-1 text-xs text-stone-500">
              Schedule reports to be automatically generated and emailed.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-stone-100">
            {MOCK_SCHEDULED.map((schedule) => {
              const typeCfg = REPORT_TYPES[schedule.type];
              const TypeIcon = typeCfg.icon;
              return (
                <div
                  key={schedule.id}
                  className="flex items-center justify-between px-6 py-4 transition-colors hover:bg-stone-50"
                >
                  <div className="flex items-center gap-4">
                    <div className={cn('rounded-lg p-2', typeCfg.iconBg)}>
                      <TypeIcon
                        className={cn('h-4 w-4', typeCfg.iconColor)}
                      />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-stone-900">
                        {schedule.name}
                      </p>
                      <p className="text-xs text-stone-500">
                        {schedule.frequency} &middot; Next: {schedule.nextRun}{' '}
                        &middot; To: {schedule.recipients}
                      </p>
                    </div>
                  </div>
                  <button className="rounded-md p-1.5 text-stone-400 transition-colors hover:bg-red-50 hover:text-red-600">
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
